### ISSUE TITLE
Feature Request : Add parts group 

### ISSUE THREAD

**Issue by vpiau** [SpinaCMS/Spina#947]
On a page template like a landing page, the number of parts can grow very quickly. 
And it becomes very hard to find a title which is enough explicit of where the part is used in template.

To organize parts, it could be great to add a `group` attribute to part definition. With this new attribute, we could visually group all parts within the same `group` attribute on the corresponding template form. 

For example, on a landing page with different sections like `hero`, `features`, `testimonials` :

```html
<section id="hero">...</section>
<section id="features">...</section>
<section id="testimonials">...</section>
```

We could define all parts included in `hero` section like this:

```ruby
theme.parts = [{
    name: 'hero_heading',
    title: "Heading",
    group: "Hero",
    part_type: "Spina::Parts::Line"
  },{
    name: 'hero_subheading',
    title: "Subheading",
    group: "Hero",
    part_type: "Spina::Parts::Multiline"
  },
{
    name: 'hero_body',
    title: "Body",
    group: "Hero",
    part_type: "Spina::Parts::Text"
  },
```

And render template edit form like this :

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/59887190/150009266-b3d2dc72-6ff3-4079-ae95-9f73d1ef5201.png">

**Comment by Bramjetten** [comment]
I like the idea of grouping fields together. I'm not 100% sure about the `group` attribute though. I think grouping should be done on the view_template itself, not on the parts.

**Comment by vpiau** [comment]
As always, the simpler, the better.
I don't  know which is the best way to implement this, but I could think about this if you want.

**Comment by Bramjetten** [comment]
How about optionally setting a hash instead of an array:
```ruby
theme.view_templates = [{
    name: 'show',
    title: 'Simple page',
    parts: {
      "Hero": %w(headline hero_image),
      "Content": %w(main)
    }
  }
```

**Comment by vpiau** [comment]
And even more explicit, with a sections array with title and optional description :

```
theme.view_templates = [{
    name: 'show',
    title: 'Simple page',
    sections: [{
       title: "Hero",
       description: "All content of hero section",
       parts: %w(headline hero_image)
    }, {
       title: "Content",
       parts: %w(main)
    }]
  }
```

**Comment by Bramjetten** [comment]
Even nicer. That way you could even combine the two.

**Comment by Bramjetten** [comment]
Created a quick WIP PR #948

**Comment by tobiasbhn** [comment]
Any progress on this?

**Comment by tobiasbhn** [comment]
To be certain, is this just about a grouped view in the backend, or an actual grouping of parts? I would favor the latter, because I have the following scenario:
I have sections on a page which are fundamentally repetitive, but differ in one part. Using a repeater is not possible due to the unique part per section. Using one part several times per page is not possible either, as far as I know. So I have to define the repeating parts several times.

Example (currently in use in a somewhat similar fashion):
```ruby
# Repetitive Section One
{ name: "section_title_one", part_type: "Spina::Part::Line" },
{ name: "section_description_one", part_type: "Spina::Part::MultiLine" },
{ name: "section_projects_selector", part_type: "Spina::Part::ProjectsSelector" }, # <- unique part in section

# Repetitive Section Two
{ name: "section_title_two", part_type: "Spina::Part::Line" }, # <- repeating part
{ name: "section_description_two", part_type: "Spina::Part::MultiLine" }, # <- repeating part
{ name: "section_articles_selector", part_type: "Spina::Part::ArticlesSelector" }, # <- unique part in section

# Repetitive Section Three
{ name: "section_title_three", part_type: "Spina::Part::Line" }, # <- repeating part
{ name: "section_description_three", part_type: "Spina::Part::MultiLine" }, # <- repeating part
{ name: "section_label_selector", part_type: "Spina::Part::LabelsSelector" }, # <- unique part in section
```

With actual grouping I could do the following:
```ruby
{ name: "title", part_type: "Spina::Part::Line" }, # <- reused part per group
{ name: "description", part_type: "Spina::Part::MultiLine" }, # <- reused part per group

{ name: "projects_selector", part_type: "Spina::Part::ProjectsSelector" }, # <- unique part in section
{ name: "articles_selector", part_type: "Spina::Part::ArticlesSelector" }, # <- unique part in section
{ name: "label_selector", part_type: "Spina::Part::LabelsSelector" }, # <- unique part in section

# Actual Sections
{ name: "section_one", part_type: "Spina::Part::Group", parts: %w(title description projects_selector) },
{ name: "section_two", part_type: "Spina::Part::Group", parts: %w(title description articles_selector) },
{ name: "section_three", part_type: "Spina::Part::Group", parts: %w(title description label_selector) }
```

This is just an Example, architecture in actual project is slightly different, but the key concept is the same. Or maybe I miss an fundamental feature of Spina to achieve same results with a better theme syntax than I currently have?

**Comment by tobiasbhn** [comment]
Last comment from my side, I swear. Then I will be quiet.
As I saw in your WIP #948, the changes so far are indeed meant to be frontend only. Would an implementation of my idea be also possible? (so implementation on part level instead of view level)
Basically the implementation is actually already in Spina, namely as `Spina::Part::RepeaterContent` (is in fact a grouping of Parts). So you could rename the Part `RepeaterContent` to Group (is it that easy?) and then make it both available to the user individually (currently `RepeaterContent` is only in the background) as well as take it as content of the repeater at the same time.

A user defined display for the grouped parts is in any case also possible on part level.
